spring:
  datasource:
    url: jdbc:mysql://localhost:3307/backend?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dlwodnr0718

  data:
    redis:
      host: localhost
      port: 6379

